### ISSUE TITLE
ワールド毎に、再生成間隔を指定できる様にして欲しい

### ISSUE THREAD

**Issue by unchama** [Mon-chi/RegenWorld#1]
具体的には、以下config.yml内のperiodical:部分を複数指定出来る様になると嬉しいです。
お忙しい所恐れ入りますが、お手すきの際に改良して頂けると幸いです。
宜しくお願い致します。

```
periodical[0]:
  date: '2018-06-29T06:00:00+09:00'
  interval: 10080
  worlds:
  - world_1
  - world_2
periodical[1]:
  date: '2018-06-29T06:00:00+09:00'
  interval: 5040
  worlds:
  - world_3
  - world_4
command:
  before:
  - say Start regenerating %world%
  after:
  - say Finish regenerating %world%
tp-world: world
```
